### ISSUE TITLE
Use my own dockerfile

### ISSUE THREAD

**Issue by ScmTble** [zeabur/docs#46]
Use my own dockerfile to deploy，can't seem to expose the port，Using the environment variable port doesn't work either 

![image](https://user-images.githubusercontent.com/56188521/224479980-d673eb48-80f7-4b0d-a625-bc57fba65a17.png)
![image](https://user-images.githubusercontent.com/56188521/224480170-74ec430d-8094-4aa5-8772-a9a6c1af190e.png)

**Comment by MichaelYuhe** [comment]
It seems that you've set the port to 8000 in the code?

**Comment by ScmTble** [comment]
The logs show running on port 8000

**Comment by yuaanlin** [comment]
> The logs show running on port 8000

Which means your program is listening on port `8000`, not the environment variable `$PORT`. So you will see the error page because Zeabur cannot expose your service.

To deploy your service on Zeabur, please modify your code to replace the hard coded `8000` to `$PORT`.

For example, if your program is developed with Node.js, you can find something similar to this in the code:

```js
app.listen(8000);
```

To fix this, change your code to:

```js
app.listen(process.env.PORT || 8000)
```

**Comment by ScmTble** [comment]
Yes,it work,thanks

**Comment by ScmTble** [comment]
I have a small suggestion . The color of the build state is more of an error, and I think it should be replaced
![image](https://user-images.githubusercontent.com/56188521/224486113-d781c22a-25f9-417c-b02e-c4db6d448614.png)

**Comment by yuaanlin** [comment]
> I have a small suggestion . The color of the build state is more of an error, and I think it should be replaced

Thanks for suggestion! We are working hard on the fresh new dashboard 2.0 design now.

For further question or suggestion, would you like to post them on our [Discord Fourm](https://discord.gg/qFfJ9Qbe) ? Thanks!

**Comment by ScmTble** [comment]
Oh yes thanks!
